config/routes.rb
Fs::Application.routes.draw do
  resources :sheets
end

app/models/sheet.rb
class ApproachesValidator < ActiveModel::Validator

  def is_valid_approach_value?(x)
    x.is_a? Integer and x.between?(-4,10)
  end

  def validate(record)
    [:careful, :clever, :flashy, :forceful, :quick, :sneaky].each  do |a|
      x = record.send(a)
      unless x.is_a? Integer and x.between?(-4,10)
        record.errors[a] << "#{a.to_s.capitalize} should be a small integer, buddy."
      end
    end
  end
    
end

class Sheet < ActiveRecord::Base
  validates :name, presence: true
  validates_with ApproachesValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController

  def index
    @sheets = Sheet.all
  end


  def new
    @sheet = Sheet.new
  end


  def create
    @sheet = Sheet.new(sheet_params)
    if @sheet.save 
      redirect_to @sheet
    else
      render 'new'
    end
  end


  def show
    @sheet = Sheet.find(params[:id])
  end


  def update
    @sheet = Sheet.find(params[:id]) 
    if @sheet.update(params[:sheet].permit!)
      redirect_to @sheet
    else
      render 'edit'
    end
  end


  def edit
    @sheet = Sheet.find(params[:id])
  end


  def destroy
    @sheet = Sheet.find(params[:id])
    @sheet.destroy
    redirect_to sheets_path
  end


  private
    def sheet_params
      params.require(:sheet).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sheet_helper.rb
module SheetHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sheets/edit.haml
=form_for :sheet, url: sheet_path(@sheet.id), method: :patch do |f|
  -if @sheet.errors.any?
    %div#errorExplanation
      %h2 
        You need to fix 
        ="#{@sheet.errors.count} "
        =pluralize(@sheet.errors.count, "error")
        before I can take this.
      %ul
        -@sheet.errors.full_messages.each do |m|
          %li
            =m

        

  %p
    =f.label :name
    =f.text_field :name
  %p
    =f.label :description
    =f.text_area :description

  %p
    =f.label :high_concept
    =f.text_field :high_concept
  %p
    =f.label :trouble
    =f.text_field :trouble
  %p
    =f.label :aspect1
    =f.text_field :aspect1
  %p
    =f.label :aspect2
    =f.text_field :aspect2
  %p
    =f.label :aspect3
    =f.text_field :aspect3


  %ul
    %li
      =f.label :careful
      =f.number_field :careful
    %li
      =f.label :clever
      =f.number_field :clever
    %li
      =f.label :flashy
      =f.number_field :flashy
    %li
      =f.label :forceful
      =f.number_field :forceful
    %li
      =f.label :quicky
      =f.number_field :quick
    %li
      =f.label :sneaky
      =f.number_field :sneaky

  %p
    =f.submit

app/views/sheets/index.haml
%h1 Fate Sheets

<ul>
-@sheets.sort {|a,b| a.name.downcase <=> b.name.downcase} .each do |s|
  %li
    =link_to "#{s.name}", controller: "sheets", action: "show", id: s.id
</ul>

=link_to "New Sheet", new_sheet_path

app/views/sheets/json.erb
<%= @sheet.to_json =%>

app/views/sheets/new.haml
=form_for :sheet, url: sheets_path do |f|
  %p
    =f.label :name
    =f.text_field :name
  %p
    =f.label :description
    =f.text_area :description

  %p
    =f.label :high_concept
    =f.text_field :high_concept
  %p
    =f.label :trouble
    =f.text_field :trouble
  %p
    =f.label :aspect1
    =f.text_field :aspect1
  %p
    =f.label :aspect2
    =f.text_field :aspect2
  %p
    =f.label :aspect3
    =f.text_field :aspect3


  %ul
    %li
      =f.label :careful
      =f.number_field :careful
    %li
      =f.label :clever
      =f.number_field :clever
    %li
      =f.label :flashy
      =f.number_field :flashy
    %li
      =f.label :forceful
      =f.number_field :forceful
    %li
      =f.label :quicky
      =f.number_field :quick
    %li
      =f.label :sneaky
      =f.number_field :sneaky

  %p
    =f.submit

app/views/sheets/show.haml
=link_to "back", controller: "sheets", action: "index"
<br/>
=link_to "Edit", edit_sheet_path(@sheet)
=link_to "Delete", sheet_path(@sheet), method: :delete, data: {confirm: "Confirm deletion:"}

%h1
  =@sheet.name
%p
  =@sheet.description

%ul#aspects
  %li
    =@sheet.high_concept
  %li
    =@sheet.trouble
  %li
    =@sheet.aspect1
  %li
    =@sheet.aspect2
  %li
    =@sheet.aspect3

%ul#approaches
  %li
    =@sheet.careful
  %li
    =@sheet.clever
  %li
    =@sheet.flashy
  %li
    =@sheet.forceful
  %li
    =@sheet.quick
  %li
    =@sheet.sneaky